#!/bin/sh -h 
dir_name=`dirname $0`
if [ "${dir_name}" = "." ]; then
    cd $dir_name
    dir_name=`pwd`
fi
if [ -d $dir_name/../../../../../../../.. ]; then
    cd $dir_name/../../../../../../../..
fi
if [ -f /home/pkchirum/Desktop/praveen_Experiments/randomization/simv.daidir/debug_dump/fsearch/.create_fsearch_db ]; then
    if [ ! -f /home/pkchirum/Desktop/praveen_Experiments/randomization/simv.daidir/debug_dump/fsearch/fsearch.db ]; then
        /home/pkchirum/Desktop/praveen_Experiments/randomization/simv.daidir/debug_dump/fsearch/.create_fsearch_db
    fi
fi
